//+------------------------------------------------------------------+
//|                                            PythonBridgeEA.mq5    |
//+------------------------------------------------------------------+
#property copyright "Your Name"
#property version   "1.00"

#include <Trade\Trade.mqh>
CTrade trade;

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
    // Read signal from file (generated by Python)
    int file_handle = FileOpen("signals.txt", FILE_READ|FILE_TXT);
    if(file_handle != INVALID_HANDLE)
    {
        string signal = FileReadString(file_handle);
        FileClose(file_handle);

        if(signal == "BUY")
        {
            trade.Buy(100);  // Open buy position (lot size 0.1)
        }
        else if(signal == "SELL")
        {
            trade.Sell(100);  // Open sell position
        }
    }
}